pages:
  # L'image Docker qui sera utilisée pour construire votre application
  image: node:lts

  before_script:
    - npm ci

  script:
    # Précisez ici les étapes de la construction de votre application
    - npm run build

  artifacts:
    paths:
      # Le dossier qui contient les fichiers construits à publier.
      # Il doit être appelé "public".
      - public

  only:
    # Déclencher un nouveau build et déployer uniquement lorsqu'il y a un push sur
    # la(les) branche(s) ci-dessous
    - main